[project]
name = "sheafshifter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cython>=3.0.12",
    "enet",
    "setuptools>=78.1.0",
]

[tool.uv.sources]
enet = { path = "lib/pyenet" }
